services:
  #server:
  #  image: server
  #  build:
  #    context: ./server
  #    dockerfile: Dockerfile
  #  restart: always
  #  ports:
  #    - "8001:3000"
  #  depends_on:
  #    - db
  goserver:
    image: goserver
    build:
      context: ./goapp
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8001:3000"
    depends_on:
      - db
  app:
    image: app
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./app/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ding@dong.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    depends_on:
      - db